name: SonarCloud
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Analyze with SonarCloud
      run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=PR-SE-Group-4_Sudoku_App -Dsonar.organization=pr-se-group-4 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=01eb15cf107641fbd5bb8e0fd0a1d8bff0ebca70
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: 01eb15cf107641fbd5bb8e0fd0a1d8bff0ebca70
